### ISSUE TITLE
Unable to Login 

### ISSUE THREAD

**Issue by joshrhoades** [steyep/alfred-jira#114]
Installed the latest build, and the first run I got the login prompt, entered all that (correctly), and got a 401 error (despite the info being correct). Tried again, and got nothing, no prompt, no error, no response at all. Killed Alfred and restarted it and still can't get any prompt. I cleaned and re-installed, logged in again (using id.atlassian.com instead of the branded URL), and got a 405 response, and could not get back to the login prompt again.

Here's the debug log from Alfred:

```
[10:44:08.857] Logging Started...
[10:44:11.448] jira[Script Filter] Queuing argument ''
[10:44:11.681] jira[Script Filter] Script with argv '(null)' finished
[10:44:11.684] STDERR: jira[Script Filter] Unable to get options. auth.checkConfig did not pass.
[10:44:11.685] jira[Script Filter] <?xml version="1.0"?>
<items>
  <item valid="yes" arg="login">
    <title>Login</title>
    <icon>/Users/USER/Downloads/alfred-jira-master/resources/icons/login.png</icon>
  </item>
</items>
[10:44:24.232] jira[Script Filter] Processing complete
[10:44:24.233] jira[Script Filter] Passing output 'login' to Run Script
[10:44:24.716] ERROR: jira[Run Script] /Users/USER/Downloads/alfred-jira-master/lib/jira/auth.js:19
      if (err) throw err;
               ^

Error: Command failed: /bin/zsh -c "eval \$(echo \"\$(/usr/libexec/path_helper -s)\" | awk -F';' '{ print \$1 }'); npm run electron login"
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module './'
Require stack:
- /Users/USER/Downloads/alfred-jira-master/node_modules/.bin/electron
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/USER/Downloads/alfred-jira-master/node_modules/.bin/electron:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/USER/Downloads/alfred-jira-master/node_modules/.bin/electron'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-jira@1.0.10 electron: `electron . "login"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-jira@1.0.10 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USER/.npm/_logs/2019-12-04T18_44_24_628Z-debug.log

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: `/bin/zsh -c "eval \\$(echo \\"\\$(/usr/libexec/path_helper -s)\\" | awk -F';' '{ print \\$1 }'); npm run electron login"`
}
[10:44:24.749] jira[Run Script] Processing complete
[10:44:24.750] jira[Run Script] Passing output '' to Post Notification
[10:47:52.404] Logging Stopped.
[10:48:38.786] Logging Started...
[10:48:40.557] jira[Script Filter] Queuing argument ''
[10:48:40.797] jira[Script Filter] Script with argv '(null)' finished
[10:48:40.799] STDERR: jira[Script Filter] Unable to get options. auth.checkConfig did not pass.
[10:48:40.799] jira[Script Filter] <?xml version="1.0"?>
<items>
  <item valid="yes" arg="login">
    <title>Login</title>
    <icon>/Users/USER/sourcecode/alfred-jira/resources/icons/login.png</icon>
  </item>
</items>
[10:48:41.339] jira[Script Filter] Processing complete
[10:48:41.340] jira[Script Filter] Passing output 'login' to Run Script
[10:49:16.750] STDERR: jira[Run Script] (node:7468) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Credentials erased!
[10:49:16.751] jira[Run Script] Processing complete
[10:49:16.752] jira[Run Script] Passing output '405: Method Not Allowed
' to Post Notification
[10:49:21.568] jira[Script Filter] Queuing argument ''
[10:49:21.828] jira[Script Filter] Script with argv '(null)' finished
[10:49:21.829] STDERR: jira[Script Filter] Unable to get options. auth.checkConfig did not pass.
[10:49:21.829] jira[Script Filter] <?xml version="1.0"?>
<items>
  <item valid="yes" arg="login">
    <title>Login</title>
    <icon>/Users/USER/sourcecode/alfred-jira/resources/icons/login.png</icon>
  </item>
</items>
[10:49:22.326] jira[Script Filter] Processing complete
[10:49:22.327] jira[Script Filter] Passing output 'login' to Run Script
[10:49:22.812] ERROR: jira[Run Script] /Users/USER/sourcecode/alfred-jira/lib/jira/auth.js:19
      if (err) throw err;
               ^

Error: Command failed: /bin/zsh -c "eval \$(echo \"\$(/usr/libexec/path_helper -s)\" | awk -F';' '{ print \$1 }'); npm run electron login"
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module './'
Require stack:
- /Users/USER/sourcecode/alfred-jira/node_modules/.bin/electron
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/USER/sourcecode/alfred-jira/node_modules/.bin/electron:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/USER/sourcecode/alfred-jira/node_modules/.bin/electron'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-jira@1.0.10 electron: `electron . "login"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-jira@1.0.10 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USER/.npm/_logs/2019-12-04T18_49_22_727Z-debug.log

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: `/bin/zsh -c "eval \\$(echo \\"\\$(/usr/libexec/path_helper -s)\\" | awk -F';' '{ print \\$1 }'); npm run electron login"`
}
[10:49:22.813] jira[Run Script] Processing complete
[10:49:22.813] jira[Run Script] Passing output '' to Post Notification
[10:49:30.127] Logging Stopped.
[10:49:31.162] Logging Started...
```

Here's the npm error log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron',
1 verbose cli   'login'
1 verbose cli ]
2 info using npm@6.13.2
3 info using node@v13.1.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle alfred-jira@1.0.10~preelectron: alfred-jira@1.0.10
6 info lifecycle alfred-jira@1.0.10~electron: alfred-jira@1.0.10
7 verbose lifecycle alfred-jira@1.0.10~electron: unsafe-perm in lifecycle true
8 verbose lifecycle alfred-jira@1.0.10~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/USER/sourcecode/alfred-jira/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle alfred-jira@1.0.10~electron: CWD: /Users/USER/sourcecode/alfred-jira
10 silly lifecycle alfred-jira@1.0.10~electron: Args: [ '-c', 'electron . "login"' ]
11 silly lifecycle alfred-jira@1.0.10~electron: Returned: code: 1  signal: null
12 info lifecycle alfred-jira@1.0.10~electron: Failed to exec electron script
13 verbose stack Error: alfred-jira@1.0.10 electron: `electron . "login"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid alfred-jira@1.0.10
15 verbose cwd /Users/USER/sourcecode/alfred-jira
16 verbose Darwin 19.0.0
17 verbose argv "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/bin/npm" "run" "electron" "login"
18 verbose node v13.1.0
19 verbose npm  v6.13.2
20 error code ELIFECYCLE
21 error errno 1
22 error alfred-jira@1.0.10 electron: `electron . "login"`
22 error Exit status 1
23 error Failed at the alfred-jira@1.0.10 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joshrhoades** [comment]
Finally got this working. I had to do something similar as #89, by deleting the `node_modules` in the package contents for the preferences and rerun `npm install`. Now it's all working.
