### ISSUE TITLE
Documentation does not clarify how to log in

### ISSUE THREAD

**Issue by m-collins** [steyep/alfred-jira#20]
Hi I'm not sure if I'm missing a trick here but it's not clear how to complete the log in step. Can you pleaseclarify

**Comment by steyep** [comment]
Once you've got the workflow installed by running `npm run build`, you can launch Alfred and type the `jira` keyword. If it's your first time using the workflow, you should be prompted to login:
![screen shot 2016-10-06 at 9 12 17 pm](https://cloud.githubusercontent.com/assets/4822034/19176110/c3facee4-8c0a-11e6-9317-57784adb7160.png)
If you press `enter` on the `login` option, you should be prompted to enter the url for your jira instance and your credentials:
![screen shot 2016-10-06 at 9 22 35 pm](https://cloud.githubusercontent.com/assets/4822034/19176138/080cf260-8c0b-11e6-96ac-64acd393acfd.png)
Does that help? What is the experience you've been having?

**Comment by arvinsim** [comment]
I have the same problem. I tried following the steps above but I don't see the login option when I type "jira"

**Comment by steyep** [comment]
Let's try and debug this:

1. Open Alfred's preferences
2. Select Workflows
3. Ensure that the Jira workflow is installed in your list of workflows.
4. Select the Jira workflow
5. Turn on debugging by clicking the bug icon
6. Select "Log all information" from the drop down menu
7. Open Alfred and type `jira`
8. Paste the feedback to this thread

Hopefully that will help pinpoint the issue.
<img width="846" alt="debug" src="https://cloud.githubusercontent.com/assets/4822034/19878135/9ab6d11c-9fbb-11e6-89ef-3873e0938f50.png">

**Comment by arvinsim** [comment]
This is what I got.

```
Starting debug for 'jira'

[2016-11-01 10:46:56][ERROR: input.scriptfilter] Code 1: /Users/------/My/AlfredWorkflows/alfred-jira/lib/scriptfilter.js:7
    let feedback = '<?xml version="1.0"?><items><item valid="no"><title>%s</title></item></items>';
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by steyep** [comment]
What version of node are you running? 
```
node -v
```

**Comment by arvinsim** [comment]
I am using `v4.2.2`

**Comment by steyep** [comment]
Okay, that's probably the problem, though, I thought that `4.x` introduced block-scope. I will take a closer look at this and determine which versions the workflow is _actually_ compatible with and see what I can do in the way of making it backwards compatible. 

In the meantime, If you're not committed to running v4 on your machine, upgrading `node` to a newer version would probably resolve the issue.

**Comment by arvinsim** [comment]
Thanks for clarifying the problem. Hope this helps other people having the same issue.

**Comment by steyep** [comment]
@arvinsim, can you also check that the version of `node` that you have installed in `/usr/local/bin` is also `>=4.0`?
```
/usr/local/bin/node -v
```

**Comment by arvinsim** [comment]
@steyep Yep, it is `v4.2.2`

**Comment by steyep** [comment]
Because the workflow uses ES2015, it currently requires `node` to be at version `v6.0.0` or later.

**Comment by arvinsim** [comment]
@steyep Ok thanks.

**Comment by proudcommerce** [comment]
hey guys,

i installed / reinstalled completely, but there is no workflow in the list :-(

> alfred-jira@1.0.1 build /Users/tobias/Dropbox/Apps/Alfred/Alfred-Jira
> sh ./bin/install.sh
> Looking for Alfred Preferences...
> Found preferences at: /Users/tobias/Library/Application Support/Alfred 3/Alfred.alfredpreferences
> Workflow already installed at "/Users/tobias/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/_jira".
> Re-install? Y/n
> Y
> Installation complete!

**Comment by steyep** [comment]
Hey @proudcommerce, my apologies for the inconvenience! 

It's worth mentioning that after installing the workflow, it takes a moment or two for Alfred to recognize it. If you restart Alfred, it should show up – provided it installed correctly.

If you restarted Alfred and it's still not showing up, let's verify that the script installed the workflow where it says it did:
```
test -d /Users/tobias/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/_jira && echo "Directory exists" || echo "Directory not found"
```

If that checks out, you might want to verify that Alfred actually stores your workflows in `/Users/tobias/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows`. The easiest way to do that is by opening Alfred's preferences, clicking "Workflows", right-click on one of your workflows and select "Open Terminal Here." Then from the Terminal run: `dirname $PWD`.

If that directory doesn't match where the build script installed it the first time, that means your workflows  are not stored in one of the default locations defined in the installation script. But that's fine, just grab the path from that previous command, switch back over to the `alfred-jira` repo, and run (replacing `{ path/to/Alfred.alfredpreferences }` with the path from the last command):
```
npm run build { path/to/Alfred.alfredpreferences }
```

**Comment by azhang** [comment]
I encountered this issue as well. Turns out that since I sync my Alfred prefs with Dropbox, this script doesn't install to the correct Alfred.alfredpreferences/workflows directory. @steyep have you looked into packaging everything up into a .alfredworkflow distributable?

**Comment by steyep** [comment]
Yes, @azhang, once I nail down an alpha release I will create a `.alfredworkflow` file for distribution. That being said, the install script checks `$HOME/Dropbox` first for the `workflow` folder so it doesn't seem like you should have experienced any issue. Can you elaborate?

**Comment by sarumont** [comment]
I saw the same issue as @azhang with install location - the shell script did not detect my Dropbox preferences. It seems, in my case at least, it's just an error with the `find` command:

```
→ find ~/Dropbox -path "*.alfredpreferences/workflows"

→ find ~/Dropbox/ -path "*.alfredpreferences/workflows"
/Users/richard/Dropbox//Alfred/Alfred.alfredpreferences/workflows
```

Due to the fact that `~/Dropbox` is a symlink:

```
→ l ~/Dropbox
lrwxr-xr-x  1 richard  staff    18B Mar 17 14:16 /Users/richard/Dropbox@ -> Dropbox (Personal)
```

This is what the macOS Dropbox app does when you're linking both a personal and business Dropbox account - it gives you `Dropbox (Personal)` and `Dropbox (<biz name>)`.

**Comment by steyep** [comment]
Oh, okay. Good to know! Thanks.

**Comment by azhang** [comment]
@steyep My dropbox dir is also `~/Dropbox (Personal)` rather than `~/Dropbox`. It doesn't seem like my dropbox installation came with a `~/Dropbox` symlink
