### ISSUE TITLE
Error with block-scoped declarations

### ISSUE THREAD

**Issue by joshferrell** [steyep/alfred-jira#32]
I'm currently running node v 7.4.0

Here is the error I get when running jira in alfred:
```
Starting debug for 'jira'

[2017-01-24 09:29:42][ERROR: input.scriptfilter] Code 1: /Users/{USERNAME}/Documents/NodeApps/alfred-jira/lib/scriptfilter.js:7
    let feedback = '<?xml version="1.0"?><items><item valid="no"><title>%s</title></item></items>';
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

**Comment by joshferrell** [comment]
I figured out that the issue was on my end with NVM. I'm closing this ticket as NVM was resetting my node version to v4.*. Reinstalling nvm fixed this issue.
