### ISSUE TITLE
Settings can fail to fetch update when cloned via ssh

### ISSUE THREAD

**Issue by sarumont** [steyep/alfred-jira#53]
I initially cloned the repo via `ssh`, and the exec of `git fetch origin` fails when I attempt to go to Settings:

```
[2017-05-18 06:56:58][STDERR: input.scriptfilter] ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
{ Error: Command failed: /bin/zsh -c ". /Users/richard/.nvm/nvm.sh && /usr/libexec/path_helper | awk '{print $1}' && git fetch origin"
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at checkExecSyncError (child_process.js:475:13)
    at Object.execSync (child_process.js:515:13)
    at Object.module.exports.execSync (/Users/richard/src/alfred-jira/lib/alfred-exec.js:15:18)
    at Object.module.exports.checkUpdates (/Users/richard/src/alfred-jira/lib/settings.js:37:10)
    at Object.module.exports.menu (/Users/richard/src/alfred-jira/lib/settings.js:52:10)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Object.ActionHandler.handle (/Users/richard/src/alfred-jira/lib/workflow.js:16:20)
    at Object.<anonymous> (/Users/richard/src/alfred-jira/lib/scriptfilter.js:116:13)
    at Module._compile (module.js:541:32)
  error: null,
  cmd: '/bin/zsh -c ". /Users/richard/.nvm/nvm.sh && /usr/libexec/path_helper | awk \'{print $1}\' && git fetch origin"',
  file: '/bin/sh',
  args: 
   [ '/bin/sh',
     '-c',
     '/bin/zsh -c ". /Users/richard/.nvm/nvm.sh && /usr/libexec/path_helper | awk \'{print $1}\' && git fetch origin"' ],
  options: 
   { shell: true,
     file: '/bin/sh',
     args: 
      [ '/bin/sh',
        '-c',
        '/bin/zsh -c ". /Users/richard/.nvm/nvm.sh && /usr/libexec/path_helper | awk \'{print $1}\' && git fetch origin"' ],
     envPairs: 
      [ 'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.DnawcXLzqP/Listeners',
        'alfred_theme=theme.fileimport.C5AAD5D0-51FB-4908-82F1-020A1B9172A3',
        'alfred_workflow_bundleid=jira.steyep',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.C4Ncz0b5GR/Render',
        'alfred_version_build=818',
        'alfred_theme_subtext=0',
        'alfred_workflow_name=jira',
        'XPC_FLAGS=0x0',
        'alfred_version=3.3.2',
        'alfred_workflow_uid=_jira',
        'SHELL=/bin/zsh',
        'alfred_workflow_cache=/Users/richard/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/jira.steyep',
        'SECURITYSESSIONID=186a7',
        'LC_CTYPE=en_US.UTF-8',
        'alfred_workflow_data=/Users/richard/Library/Application Support/Alfred 3/Workflow Data/jira.steyep',
        'PATH=/Users/richard/.local/bin:/Users/richard/.dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/android/platform-tools:/opt/android/tools:/usr/local/heroku/bin:/Users/richard/.rvm/bin:.',
        'DISPLAY=/private/tmp/com.apple.launchd.3n6nOPxRsT/org.macosforge.xquartz:0',
        'alfred_theme_selection_background=rgba(254,255,254,0.00)',
        'alfred_debug=1',
        'HOME=/Users/richard',
        'TMPDIR=/var/folders/5p/ftxr4z5n5915w20bsygjpz300000gn/T/',
        'USER=richard',
        'alfred_preferences=/Users/richard/Dropbox (Personal)/Alfred/Alfred.alfredpreferences',
        'LOGNAME=richard',
        'XPC_SERVICE_NAME=com.runningwithcrayons.Alfred-3.8372',
        '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
        'alfred_theme_background=rgba(43,61,80,0.80)',
        'alfred_preferences_localhash=eee440200d9614aceb7084b808c180df6ba65a86',
        'SHLVL=0',
        'PWD=/Users/richard/src/alfred-jira',
        'OLDPWD=/Users/richard/src/alfred-jira',
        'EDITOR=/usr/bin/vim',
        'ANDROID_HOME=/opt/android',
        'GWT_HOME=/opt/gwt',
        'HEROKU_HOME=/usr/local/heroku',
        'MAVEN_OPTS=-Djava.awt.headless=true',
        'MAVEN_ARGS=-Dvs.config.dir=build -Dnf.config.dir=build',
        'BOX_COLOR=\u001b[38;5;251m',
        '_=/Users/richard/.nvm/versions/node/v6.3.1/bin/node',
        'NODE_TLS_REJECT_UNAUTHORIZED=0' ],
     stdio: [ [Object], [Object], [Object] ] },
  envPairs: 
   [ 'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.DnawcXLzqP/Listeners',
     'alfred_theme=theme.fileimport.C5AAD5D0-51FB-4908-82F1-020A1B9172A3',
     'alfred_workflow_bundleid=jira.steyep',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.C4Ncz0b5GR/Render',
     'alfred_version_build=818',
     'alfred_theme_subtext=0',
     'alfred_workflow_name=jira',
     'XPC_FLAGS=0x0',
     'alfred_version=3.3.2',
     'alfred_workflow_uid=_jira',
     'SHELL=/bin/zsh',
     'alfred_workflow_cache=/Users/richard/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/jira.steyep',
     'SECURITYSESSIONID=186a7',
     'LC_CTYPE=en_US.UTF-8',
     'alfred_workflow_data=/Users/richard/Library/Application Support/Alfred 3/Workflow Data/jira.steyep',
     'PATH=/Users/richard/.local/bin:/Users/richard/.dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/android/platform-tools:/opt/android/tools:/usr/local/heroku/bin:/Users/richard/.rvm/bin:.',
     'DISPLAY=/private/tmp/com.apple.launchd.3n6nOPxRsT/org.macosforge.xquartz:0',
     'alfred_theme_selection_background=rgba(254,255,254,0.00)',
     'alfred_debug=1',
     'HOME=/Users/richard',
     'TMPDIR=/var/folders/5p/ftxr4z5n5915w20bsygjpz300000gn/T/',
     'USER=richard',
     'alfred_preferences=/Users/richard/Dropbox (Personal)/Alfred/Alfred.alfredpreferences',
     'LOGNAME=richard',
     'XPC_SERVICE_NAME=com.runningwithcrayons.Alfred-3.8372',
     '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
     'alfred_theme_background=rgba(43,61,80,0.80)',
     'alfred_preferences_localhash=eee440200d9614aceb7084b808c180df6ba65a86',
     'SHLVL=0',
     'PWD=/Users/richard/src/alfred-jira',
     'OLDPWD=/Users/richard/src/alfred-jira',
     'EDITOR=/usr/bin/vim',
     'ANDROID_HOME=/opt/android',
     'GWT_HOME=/opt/gwt',
     'HEROKU_HOME=/usr/local/heroku',
     'MAVEN_OPTS=-Djava.awt.headless=true',
     'MAVEN_ARGS=-Dvs.config.dir=build -Dnf.config.dir=build',
     'BOX_COLOR=\u001b[38;5;251m',
     '_=/Users/richard/.nvm/versions/node/v6.3.1/bin/node',
     'NODE_TLS_REJECT_UNAUTHORIZED=0' ],
  stderr: <Buffer 73 73 68 5f 61 73 6b 70 61 73 73 3a 20 65 78 65 63 28 2f 75 73 72 2f 58 31 31 52 36 2f 62 69 6e 2f 73 73 68 2d 61 73 6b 70 61 73 73 29 3a 20 4e 6f 20 ... >,
  stdout: <Buffer 50 41 54 48 3d 22 2f 75 73 72 2f 6c 6f 63 61 6c 2f 62 69 6e 3a 2f 75 73 72 2f 62 69 6e 3a 2f 62 69 6e 3a 2f 75 73 72 2f 73 62 69 6e 3a 2f 73 62 69 6e ... >,
  pid: 27700,
  output: 
   [ null,
     <Buffer 50 41 54 48 3d 22 2f 75 73 72 2f 6c 6f 63 61 6c 2f 62 69 6e 3a 2f 75 73 72 2f 62 69 6e 3a 2f 62 69 6e 3a 2f 75 73 72 2f 73 62 69 6e 3a 2f 73 62 69 6e ... >,
     <Buffer 73 73 68 5f 61 73 6b 70 61 73 73 3a 20 65 78 65 63 28 2f 75 73 72 2f 58 31 31 52 36 2f 62 69 6e 2f 73 73 68 2d 61 73 6b 70 61 73 73 29 3a 20 4e 6f 20 ... > ],
  signal: null,
  status: 128 }
```

The workaround is to update to `https`:

```
git remote set-url origin https://github.com/steyep/alfred-jira.git
```

Or clone via `https` in the beginning.

**Comment by steyep** [comment]
Thanks for pointing this out. For what it's worth, the ssh issue could be related to your OS. You wouldn't happen to be running  MacOS Sierra v10.12 would you? There have been [reports of a "bug"](https://github.com/lionheart/openradar-mirror/issues/15361) that have caused similar issues. I have this line in my `.zshrc` file and I've been using ssh as my origin's remote with no issue:
```
# Load private key passphrases from MacOS Keychain
{ [[ "`pgrep ssh-agent`" ]] || eval `ssh-agent`; ssh-add -A;  } &>/dev/null
```

But regardless, of the reason it was still an exception that needed to be caught so I've merged a hotfix to `master`. Thanks again!

**Comment by sarumont** [comment]
Yeah, I'm on 10.12. I have worked around that "bug" by just `kill`ing and restarting `ssh-agent` when I reboot (since that doesn't often happen). Thanks for pointing out other workarounds and the hotfix!
