### ISSUE TITLE
Unable to Login (electron error)

### ISSUE THREAD

**Issue by mbulman** [steyep/alfred-jira#71]
Hi,

I get a JS error when trying to Login for the first time.  I search for "electron" in past issues, but none of them line up with what I'm seeing.

I'm running node 8.2.0 and npm 5.3.0, both from /usr/local/bin, installed via homebrew

Full Alfred debug output:
```
[2017-08-30 17:45:57][input.scriptfilter] Queuing argument ''
[2017-08-30 17:45:58][input.scriptfilter] Script with argument '(null)' finished
[2017-08-30 17:45:58][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-08-30 17:45:58][input.scriptfilter] <?xml version="1.0"?>
<items>
  <item valid="yes" arg="login">
    <title>Login</title>
    <icon>/Users/mbulman/src/alfred-jira/resources/icons/login.png</icon>
  </item>
</items>
[2017-08-30 17:45:59][input.scriptfilter] Processing output of 'action.script' with arg 'login'
[2017-08-30 17:46:01][ERROR: action.script] /Users/mbulman/src/alfred-jira/lib/jira/auth.js:19
      if (err) throw err;
               ^

Error: Command failed: /bin/bash -c "eval $(/usr/libexec/path_helper | awk '{print $1}') npm run electron login"
module.js:487
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mbulman/src/alfred-jira/node_modules/.bin/electron:3:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-jira@1.0.5 electron: `electron . "login"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-jira@1.0.5 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbulman/.npm/_logs/2017-08-30T22_46_00_941Z-debug.log

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
[2017-08-30 17:46:01][action.script] Processing output of 'output.notification' with arg ''
```

Output of /Users/mbulman/.npm/_logs/2017-08-30T22_46_00_941Z-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron',
1 verbose cli   'login' ]
2 info using npm@5.3.0
3 info using node@v8.2.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle alfred-jira@1.0.5~preelectron: alfred-jira@1.0.5
6 info lifecycle alfred-jira@1.0.5~electron: alfred-jira@1.0.5
7 verbose lifecycle alfred-jira@1.0.5~electron: unsafe-perm in lifecycle true
8 verbose lifecycle alfred-jira@1.0.5~electron: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mbulman/src/alfred-jira/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle alfred-jira@1.0.5~electron: CWD: /Users/mbulman/src/alfred-jira
10 silly lifecycle alfred-jira@1.0.5~electron: Args: [ '-c', 'electron . "login"' ]
11 silly lifecycle alfred-jira@1.0.5~electron: Returned: code: 1  signal: null
12 info lifecycle alfred-jira@1.0.5~electron: Failed to exec electron script
13 verbose stack Error: alfred-jira@1.0.5 electron: `electron . "login"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid alfred-jira@1.0.5
15 verbose cwd /Users/mbulman/src/alfred-jira
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.2.0_1/bin/node" "/usr/local/bin/npm" "run" "electron" "login"
18 verbose node v8.2.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error alfred-jira@1.0.5 electron: `electron . "login"`
22 error Exit status 1
23 error Failed at the alfred-jira@1.0.5 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks

**Comment by steyep** [comment]
Can you run `npm update` from the `alfred-jira` directory and let me know if that resolves the issue?

**Comment by mbulman** [comment]
That worked. Thanks!

Note: I had to do some file removal dancing to get npm update to succeed.  Probably should've just wiped out node_modules in the first place

**Comment by steyep** [comment]
Cool I'm glad that worked. Sorry for the issues!
