### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Soprano74** [steyep/alfred-jira#77]
I have tried using several URLs to our Jira server, but it fails:

[2017-10-25 10:09:52][input.scriptfilter] Processing output of 'action.script' with arg 'login'
[2017-10-25 10:10:11][ERROR: action.script] Unable to parse JSON response from stdout SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at /Users/tscheffer/git/alfred-jira/lib/jira/auth.js:24:23
    at ChildProcess.exithandler (child_process.js:264:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:555:12)
[2017-10-25 10:10:11][action.script] Processing output of 'output.notification' with arg 'Login canceled

Do  you need more info for debugging?

**Comment by steyep** [comment]
Are you running High Sierra by chance? I wonder if this is the same issue that is addressed by [this](https://github.com/steyep/alfred-jira/pull/76) pull request. I haven't had an opportunity to thoroughly test his fix yet but I'd be his patch would address your issue.

**Comment by Soprano74** [comment]
Yes and yes, running High Sierra and this patch works for me!

Thanks for the quick reply.
