### ISSUE TITLE
Not able to login in macOS High Sierra

### ISSUE THREAD

**Issue by tonymoxtra** [steyep/alfred-jira#80]
After I click login, it returns "Login Canceled" and consoled below:

> [2017-10-25 16:21:40][ERROR: action.script] Unable to parse JSON response from stdout SyntaxError: Unexpected number in JSON at position 4
    at Object.parse (native)
    at /Users/tonyxu/Dev/Github/alfred-jira/lib/jira/auth.js:25:23
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

Then I modified code and print out stdout:

> [2017-10-25 16:21:40][action.script] Processing output of 'output.notification' with arg '2017-10-25 16:21:26.452 Electron[25903:14927948] *** WARNING: Textured window <AtomNSWindow: 0x7ff542f33300> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2017-10-25 16:21:35.125 Electron Helper[25907:14928005] Couldn't set selectedTextBackgroundColor from default ()
{"url":"https://jira.xxxx.com/","user":"xxxx"}
Login canceled
'

**Comment by tonymoxtra** [comment]
Issue resolved by https://github.com/steyep/alfred-jira/pull/76#pullrequestreview-72044745
