### ISSUE TITLE
Error is thrown parsing JSON when attempting to log in

### ISSUE THREAD

**Issue by jhopper28** [steyep/alfred-jira#90]
Using the same credentials to sign in that I do in JIRA, I recently starting getting the following error and am unable to use the workflow:
```
[2017-12-19 17:55:25][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-12-19 17:56:00][ERROR: action.script] Unable to parse JSON response from stdout SyntaxError: Unexpected number in JSON at position 4
    at Object.parse (native)
    at /Users/Jeff/Library/Mobile Documents/com~apple~CloudDocs/Dev/alfred-jira/lib/jira/auth.js:24:23
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by steyep** [comment]
@jhopper28 sorry for the delayed response! Do you get that output when trying to view one of your "bookmarks" or when as soon as you type `jira`? Are you able to open the settings app?

I'd ensure that the settings file is located where the workflow expects it to be (`~/.alfred-jira/config.json`). You might also be able to "reset" things by logging out and then logging back in. 

Can you also verify that you're on the latest version (`1.0.8`)?

**Comment by steyep** [comment]
This has been resolved with the `v.1.0.10` release
