### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by alexsanjoseph** [steyep/alfred-jira#99]
Hi I had Alfred-Jira working fine previously, but some time back it has stopped working. This is the error from the debugger -

```
[2018-08-07 10:35:39][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2018-08-07 10:35:46][ERROR: action.script] /Users/alexsanjoseph/Work/alfred-jira/lib/jira/auth.js:19
      if (err) throw err;
               ^

Error: Command failed: /bin/zsh -c "eval \$(echo \"\$(/usr/libexec/path_helper -s)\" | awk -F';' '{ print \$1 }'); npm run electron login"
module.js:549
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alexsanjoseph/Work/alfred-jira/node_modules/.bin/electron:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-jira@1.0.8 electron: `electron . "login"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-jira@1.0.8 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexsanjoseph/.npm/_logs/2018-08-07T05_05_46_775Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
```

Can you help me figure out what's wrong?

I'm on node v8.11.3 (latest)

**Comment by alexsanjoseph** [comment]
Reinstalling even after deleting the prefences didn't seem to fix the problem. After a lot of trial, and even though the repo was up-to-date, I deleted the repo and cloned again and reinstalled. 

Seems to work from then. Closing the issue

**Comment by steyep** [comment]
@alexsanjoseph I'm glad you were able to get your issue resolved but I'm sorry to hear that you had to completely reinstall the workflow to do so. 

I'll just mention this for posterity: my guess is that one of the workflow's dependencies had become outdated (presumably `electron`). If it happens again, I would recommend running `npm update` first before having to try the "nuclear" option and reinstall. 

But again, I'm sorry for the inconvenience!
